# Generated by Django 5.1 on 2024-08-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="set",
            name="note",
        ),
        migrations.AddField(
            model_name="workoutset",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
