# Generated by Django 5.1 on 2024-08-25 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_remove_set_note_workoutset_note_alter_exercise_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='set',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='workout',
        ),
        migrations.AddField(
            model_name='set',
            name='resistance',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='set',
            name='seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual', to='exercise.set'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='planned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned', to='exercise.set'),
        ),
        migrations.AddConstraint(
            model_name='set',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reps__isnull', False), ('seconds__isnull', True)), models.Q(('reps__isnull', True), ('seconds__isnull', False)), _connector='OR'), name='reps_seconds_xor'),
        ),
        migrations.AddConstraint(
            model_name='set',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pounds__isnull', False), ('resistance__exact', '')), models.Q(('pounds__isnull', True), ('resistance__gt', '')), _connector='OR'), name='pounds_resistance_xor'),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercise.workout'),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='exercise.workoutexercise'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.UniqueConstraint(fields=('workout', 'exercise'), name='unique_workout_exercise'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('workout', 'order'), name='unique_workout_order'),
        ),
    ]
