# Generated by Django 5.1 on 2024-08-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0003_workoutexercise_remove_set_exercise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
