# Generated by Django 5.1 on 2024-08-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0004_workout_completed"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workout",
            constraint=models.UniqueConstraint(
                condition=models.Q(("completed", False)),
                fields=("completed",),
                name="unique_uncompleted_workout",
            ),
        ),
    ]
