# Generated by Django 5.1 on 2024-09-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0005_workout_unique_uncompleted_workout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="workout",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("completed", False), ("date__isnull", False), _connector="OR"
                ),
                name="completed_workout_date_not_null",
            ),
        ),
    ]
