# Generated by Django 5.1 on 2024-09-09 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0006_alter_workout_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutset",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="workoutset",
            name="actual",
        ),
        migrations.RemoveField(
            model_name="workoutset",
            name="planned",
        ),
        migrations.AddField(
            model_name="set",
            name="exercise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sets",
                to="exercise.exercise",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="WorkoutExercise",
        ),
        migrations.DeleteModel(
            name="WorkoutSet",
        ),
    ]
