# Generated by Django 5.1 on 2024-09-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0009_remove_set_pounds_resistance_xor_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="set",
            name="pounds_resistance_or",
        ),
        migrations.AddConstraint(
            model_name="set",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("resistance__exact", ""),
                    models.Q(("pounds__isnull", True), ("resistance__gt", "")),
                    _connector="OR",
                ),
                name="pounds_resistance_constraint",
            ),
        ),
    ]
