# Generated by Django 5.1 on 2024-09-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0012_remove_set_reps_seconds_xor"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="set_num",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
