# Generated by Django 5.1 on 2024-09-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0013_set_set_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='resistance',
            new_name='note',
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_seconds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_sides',
            field=models.BooleanField(default=False),
        ),
    ]
