# Generated by Django 5.1 on 2024-09-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0014_rename_resistance_set_note_exercise_is_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
