# Generated by Django 5.1 on 2024-09-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0016_rename_reps_set_reps_or_secs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='seconds',
        ),
    ]
