# Generated by Django 5.1 on 2024-10-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0017_remove_set_seconds'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='set',
            unique_together={('exercise', 'set_num')},
        ),
    ]
